# Generated by Django 5.1.2 on 2024-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_internshipapplication_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
