# Generated by Django 5.1.2 on 2024-10-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_alter_internshipapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
