# Generated by Django 5.1.2 on 2024-10-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_alter_internshipapplication_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
