# Generated by Django 5.1.2 on 2024-10-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='applly_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='internships.internship'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
