# Generated by Django 5.1.2 on 2024-11-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_remove_internshipapplication_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='descquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desc_questions', to='internships.internship'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='internships.internship'),
        ),
    ]
