# Generated by Django 5.1.2 on 2024-11-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_alter_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='applicant',
        ),
    ]
