# Generated by Django 5.1.2 on 2024-11-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_examsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_settings', to='internships.internship'),
        ),
    ]
